import Head from 'next/head';
import HomePage from '../components/Home';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div>
            <Head>
                <title> Create Next App </title>{' '}
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
                <title>Duy Hoang</title>
            </Head>
            <HomePage/>
        </div>
    );
}
